services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-uat
    container_name: teleese_api_uat
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
