services:
  api-teleese:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: teleese_api_prod
    ports:
      - "5000:5000"
    env_file:
      - .env.production
    networks:
      - shared-network

  
  loki-teleese:
    image: grafana/loki:2.9.1
    container_name: loki_api_teleese
    ports:
      - "3200:3100"
    volumes:
      - ./src/core/config/loki/config.prod.yml:/etc/loki/local-config.yml
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - shared-network

  promtail-teleese:
    image: grafana/promtail:2.9.1
    ports:
      - "9180:9080"
    container_name: promtail_api_teleese
    volumes:
      - ./src/core/config/promtail/config.prod.yml:/etc/promtail/promtail-config.yml
      - ./logs:/var/log
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - shared-network

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana_api_teleese
    ports:
      - "5100:3000"
    depends_on:
      - loki-teleese
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - shared-network

volumes:
  grafana:

networks:
  shared-network:
    external: true
