services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teleese_api_prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://195.35.25.116:27017/teleese
