services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-uat
    container_name: teleese_api_uat
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=uat
      - MONGO_URI=mongodb://195.35.25.116:27017/teleese_uat
