services:
  api-teleese:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teleese_api_prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://195.35.25.116:27017/teleese

  
  loki-teleese:
    image: grafana/loki:2.9.1
    container_name: loki_api_teleese
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki:/etc/loki
    restart: always

  promtail-teleese:
    image: grafana/promtail:2.9.1
    container_name: promtail_api_teleese
    volumes:
      - ./logs:/var/log
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
    restart: always

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana_api_teleese
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
