services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teleese_api_prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
